name: climatechecker-dev
services:
  db:
    image: mariadb:11
    container_name: climatechecker-dev-db
    environment:
      MYSQL_ROOT_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      MYSQL_DATABASE: ${SPRING_DATASOURCE_SCHEME}
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 3

  smtp:
    image: mailserver/docker-mailserver:latest
    container_name: climatechecker-dev-smtp
    hostname: mail
    domainname: example.com
    environment:
      MAILSERVER_RELAY_HOST: ${MAILSERVER_RELAY_HOST}
      MAILSERVER_RELAY_PORT: ${MAILSERVER_RELAY_PORT}
      MAILSERVER_RELAY_USER: ${MAILSERVER_RELAY_USER}
      MAILSERVER_RELAY_PASSWORD: ${MAILSERVER_RELAY_PASSWORD}
    ports:
      - "25:25"
      - "587:587"
      - "993:993"

  backend:
    build: .
    image: climatechecker-springboot:dev
    container_name: climatechecker-dev-backend
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      MAILSERVER_RELAY_HOST: ${MAILSERVER_RELAY_HOST}
      MAILSERVER_RELAY_PORT: ${MAILSERVER_RELAY_PORT}
      MAILSERVER_RELAY_USER: ${MAILSERVER_RELAY_USER}
      MAILSERVER_RELAY_PASSWORD: ${MAILSERVER_RELAY_PASSWORD}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      ROOT_USER_FIRSTNAME: ${ROOT_USER_FIRSTNAME}
      ROOT_USER_LASTNAME: ${ROOT_USER_LASTNAME}
      ROOT_USER_EMAIL: ${ROOT_USER_EMAIL}
      ROOT_USER_PASSWORD: ${ROOT_USER_PASSWORD}
    ports:
      - "8082:8082"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ../../Software-FrontEnd/
      dockerfile: Dockerfile
      target: dev
    image: climatechecker-frontend:dev
    container_name: climatechecker-dev-frontend
    environment:
      VITE_BACKEND_API_URL: ${VITE_BACKEND_API_URL}
    ports:
      - "5173:5173"
    depends_on:
      - backend