version: "3.7"
services:
  nginx_service:
    container_name: nginx
    restart: always
    build:
      context: /home/student/dev/Software-FrontEnd/
      dockerfile: Dockerfile.release
    ports:
      - 80:80
    networks:
      springapimysql-net:
        ipv4_address: 172.20.0.12
    volumes:
      - ./res/nginx.conf:/etc/nginx/conf.d/default.conf

  api_service:
    container_name: backend
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8082:8082
    depends_on:
      - mariadb
    networks:
      springapimysql-net:
        ipv4_address: 172.20.0.11
    environment:
      - spring.datasource.url=jdbc:mariadb://mariadb:3306/ontdekstation013?allowPublicKeyRetrieval=true
    volumes:
      - .m2:/root/.m2

  mariadb:
    container_name: database
    image: "mariadb:lts"
    restart: always
    ports:
      - 3306:3306
    networks:
      springapimysql-net:
        ipv4_address: 172.20.0.10
  
    environment:
      MYSQL_DATABASE: ontdekstation013
      MYSQL_USER: ontdekstation
      MYSQL_PASSWORD: ontdekstation013
      MYSQL_ROOT_PASSWORD: ontdekstation
    volumes:
      - "./res/dump-ontdekstation013-202311271246.sql:/docker-entrypoint-initdb.d/1.sql"

networks:
  springapimysql-net:
    ipam:
      config:
        - subnet: 172.20.0.0/16
