version: "3.7"
services:
  api_service:
    build: .
    restart: always
    ports:
      - 8082:8082
    networks:
      - springapimysql-net
    environment:
      - spring.datasource.url=jdbc:mariadb://mariadb:3306/ontdekstation013?allowPublicKeyRetrieval=true
    depends_on:
      - mariadb

    volumes:
      - .m2:/root/.m2

  mariadb:
    image: "mariadb:lts"
    restart: always
    ports:
      - 3306:3306
    networks:
      - springapimysql-net
    environment:
      MYSQL_DATABASE: ontdekstation013
      MYSQL_USER: ontdekstation
      MYSQL_PASSWORD: ontdekstation013
      MYSQL_ROOT_PASSWORD: ontdekstation
networks:
  springapimysql-net: