name: Build and Test

on:
  push:
    branches: 
    - main
    - s3nj24_dev #Change to your own dev branch
  pull_request:
    branches: 
    - main
    - s3nj24_dev #Change to your own dev branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
           
      - name: Create the JAR file with Maven
        run: mvn package -DskipTests  
        working-directory: ClimateChecker

  test:
   runs-on: ubuntu-latest
   needs: build

   steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
         java-version: '21'
         distribution: 'temurin'

      - name: Create JAR file with Maven
        run: mvn package -DskipTests
        working-directory: ClimateChecker
        
      - name: Run unit-tests
        run: mvn test
        working-directory: ClimateChecker

  #release:
  # runs-on: ubuntu-latest
  # needs: build

  # steps:
  #    - uses: actions/checkout@v3
  #    - name: log in to dockerhub
  #      uses: docker/login-action@v2
  #      with:
  #       username: ${{secrets.DOCKER_USERNAME}} #(Add the username to the github secrets first with the variable name "DOCKER_USERNAME")
  #       password: ${{secrets.DOCKER_PASSWORD}} #(Add the password to github secrets, for safety use a personal access token)

  #     - name: Build docker image
  #       run: docker build -t ${{secrets.DOCKER_USERNAME}}/Climatechecker-Backend .  #"Climatechecker-Backend" can be changed to a different name

  #     - name: Push docker image
  #       run: docker push ${{secrets.DOCKER_USERNAME}}/Climatechecker-Backend #Needs to be the same tag as in the docker build

  
