name: Java CI with Maven

on:
  push:
    branches: [ "s3vj23" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
           
      - name: Create the JAR file with Maven
        run: mvn package
        working-directory: ClimateChecker
