name: Sonar Scan

on:
  push:
    branches:
      - "*"

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build Project with Java 21
        run: mvn clean install -DskipTests
        working-directory: ClimateChecker

      - name: Install SonarScanner 10.6
        run: |
          curl -sSLo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-10.6.0.31212-linux.zip
          unzip sonar-scanner.zip
          sudo mv sonar-scanner-10.6.0.31212-linux /opt/sonar-scanner
          sudo ln -s /opt/sonar-scanner/bin/sonar-scanner /usr/local/bin/sonar-scanner

      - name: SonarQube Scan
        run: |
          cd ClimateChecker
          sonar-scanner
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: 'https://sonarcloud.io/'
